name: Build release ZIP

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install npm dependencies
        run: yarn install

      - name: Run npm build script
        run: yarn run build

      - name: Set up PHP
        uses: shivammathur/setup-php@v2

      - name: Install Composer dependencies
        run: composer install --no-dev -o

      - name: Commit build files
        run: |
          git config user.email "you@example.com"
          git config user.name "Your Name"
          git add -f build
          git add -f vendor
          git commit -m"Adding build files"

      - name: Generate ZIP file name
        id: repo_name
        run: echo "ZIP_FILE=${{ github.event.repository.name }}-${{ github.ref_name }}.zip" >> $GITHUB_ENV

      - name: Create Git archive
        run: git archive HEAD -o ${{ env.ZIP_FILE }}

      - name: Release ZIP file
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIP_FILE }}
          append_body: true
          body: |
            **Plugin ZIP:** [${{ env.ZIP_FILE }}](https://github.com/2ndkauboy/${{ github.event.repository.name }}/releases/download/${{ github.ref_name }}/${{ env.ZIP_FILE }}).
